### PR TITLE
CB-13175: fixing windows8.1 crash on startup

### PR DESCRIPTION
**Pull request by kaplanmaxe**
### Platforms affected

windows

### What does this PR do?

Ticket: https://issues.apache.org/jira/browse/CB-13175
 
This issue is a follow-up to [CB-12784](https://github.com/apache/cordova-windows/pull/232)

The user added the fix in `cordova-js-src/splashscreen.js` however it needs to be added to `template/www/cordova.js` as well. This PR takes the already accepted fix and applies it to `cordova.js` as well.

### What testing has been done on this change?

Ran on Windows 10 Creators Update (build 15063.250), Ran on Windows 8.1, Ran on Windows 10 mobile

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by spacepope** [comment]
👍 
I also ran into this issue and i can't understand why this is not already merged, as the PR fix for splashscreen was merged 6 month ago!
And sadly there still is no new npm package version..

**Comment by janpio** [comment]
> And sadly there still is no new npm package version..

What exactly do you mean by that?

**Comment by spacepope** [comment]
> What exactly do you mean by that?

@janpio i meant that if you now do a `cordova platform add windows` you get the latest version 5.0.0 via npm, which deploys a `platforms/windows/www/cordova-js-src/splashscreen.js` version **without** https://github.com/apache/cordova-windows/commit/279816743f995510a1070a0bf77a3180f11e468a#diff-10f029caaf05c692c305d2484da63b2d changes!
I can't understand why the current npm package still doesn't include a hotfix merged six month ago..

**Comment by janpio** [comment]
> I can't understand why the current npm package still doesn't include a hotfix merged six month ago..

Because nobody did a release in that time frame. See here for the unreleased commits: https://github.com/apache/cordova-windows/compare/5.0.0...master

**Comment by janpio** [comment]
@alsorokin So this PR's changes to `template/www/cordova.js` are good to merge as well so they would appear in the next release?

**Comment by alsorokin** [comment]
@janpio there is no need to merge this PR, because the release process includes automatic update of `cordova.js` by coho.

**Comment by janpio** [comment]
Ok, then we can close this.

Thanks for the Pull Request @kaplanmaxe. I will try to push for a release of cordova-windows that will include a fix for this per what @alsorokin described.

**Comment by alsorokin** [comment]
@janpio thanks and good luck with the release! I'll try and find some time to test it when vote is out 😃

**Comment by brodybits** [comment]
> @janpio there is no need to merge this PR, because the release process includes automatic update of cordova.js by coho.

Can we PLEASE get this issue (<https://issues.apache.org/jira/browse/CB-13175>) resolved ASAP? I just wasted almost half a day making notes about this one.

**Comment by brodybits** [comment]
WORKAROUND HACK SOLUTION is to simply apply the changes in <https://github.com/apache/cordova-windows/pull/232> for CB-12784 by hand:
* replace `appView.titleBar` with `isWin10UWP` in `colorizeTitleBar` and `revertTitleBarColor` functions in cordova.js (right around the place where it crashes with the uncaught exception).

Additional links:
- Further description along with the workaround solution in <https://github.com/brodybits/cordova-notes/issues/3>
- CB-13796 (<https://issues.apache.org/jira/browse/CB-13796>) with duplicate report that I raised before finding this one (CB-13175 / <https://github.com/apache/cordova-windows/pull/239>)

**Comment by alsorokin** [comment]
@brodybits hey, it looks like we have some unusual delay with the release, so I went ahead and pushed the changes from this PR to the repo, so at least it should work from master now.

**Comment by brodybits** [comment]
> I went ahead and pushed the changes from this PR to the repo. At least it should work from master now.

It works on Windows 8.1 from master, THANK YOU @alsorokin!

I am still looking forward to the actual release (along with others).

**Comment by brodybits** [comment]
This issue is fixed in 2e597ef1084088341b102d6e4c6a8ea465f7dce1 which will be in 5.1. But 5.1 is now held up due to some test failures as discussed in PR #246. Is it possible that we can cherry-pick 2e597ef1084088341b102d6e4c6a8ea465f7dce1 on the `5.0.x` branch and release it there?

I would like to see this resolved ASAP for Windows 8.1. I would be happy to raise a new PR to cherry-pick this on the `5.0.x` branch if it would help.

**Pull request closed without merging**
