### PR TITLE
CB-10622 fix targetsize images being ignored

### PR DESCRIPTION
**Pull request by andorman**

### CODE REVIEW

**Comment by andorman** [comment]
@sgrebnov Sorry for screwing up my previous PR, I opened a new one instead. I hope it's alright this time.

**Comment by nikhilkh** [comment]
I'm curious - is this a recent regression?

**Comment by vladimir-kotikov** [comment]
From what i understand the corresponding JIRA contains two separate issues and one of them is a regression (see apache/cordova-lib#392), but second one isn't (the one fixed by this change).

@andorman, what if both `scale` and `targetsize` qualifiers present in image name? Would image then get copied properly?

**Comment by andorman** [comment]
@vladimir-kotikov The supported image types and namings can be found here: 
https://msdn.microsoft.com/en-us/library/windows/apps/mt412102.aspx
Either "scale" or "targetsize" should be provided. Though, I see that "targetsize-*_altform-unplated" images will still be ignored. The regex should be modified to include those as well.

**Comment by SunboX** [comment]
You should allow scale 200 images for UWP10 apps. The scale 100 images look a bit blurry on a Lumia 950 and scale 240 is no longer supported:

```js
    // Platform default images
    var platformImages = [
        {dest: 'Square150x150Logo.scale-100.png', width: 150, height: 150},
        {dest: 'Square150x150Logo.scale-200.png', width: 300, height: 300},
        {dest: 'Square30x30Logo.scale-100.png', width: 30, height: 30},
        {dest: 'StoreLogo.scale-100.png', width: 50, height: 50},
        {dest: 'SplashScreen.scale-100.png', width: 620, height: 300},
        {dest: 'SplashScreen.scale-200.png', width: 1240, height: 600},
        // scaled images are specified here for backward compatibility only so we can find them by size
        {dest: 'StoreLogo.scale-240.png', width: 120, height: 120},
        {dest: 'Square44x44Logo.scale-100.png', width: 44, height: 44},
        {dest: 'Square44x44Logo.scale-200.png', width: 88, height: 88},
        {dest: 'Square44x44Logo.scale-240.png', width: 106, height: 106},
        {dest: 'Square70x70Logo.scale-100.png', width: 70, height: 70},
        {dest: 'Square71x71Logo.scale-100.png', width: 71, height: 71},
        {dest: 'Square71x71Logo.scale-200.png', width: 142, height: 142},
        {dest: 'Square71x71Logo.scale-240.png', width: 170, height: 170},
        {dest: 'Square150x150Logo.scale-240.png', width: 360, height: 360},
        {dest: 'Square310x310Logo.scale-100.png', width: 310, height: 310},
        {dest: 'Square310x310Logo.scale-200.png', width: 620, height: 620},
        {dest: 'Wide310x150Logo.scale-100.png', width: 310, height: 150},
        {dest: 'Wide310x150Logo.scale-240.png', width: 744, height: 360},
        {dest: 'SplashScreenPhone.scale-240.png', width: 1152, height: 1920}
    ];
```

**Comment by vladimir-kotikov** [comment]
@SunboX, for adding icons with scale factors other than `scale-100` and `scale-240` you need to use `target` attribute as following:
```xml
    <icon src="res/Windows/Square71x71Logo.png" target="Square71x71Logo.png" />
```
instead of adding separate `<icon ...>` tag for each image
```xml
    <icon src="res/Windows/Square71x71Logo.scale-100.png" width="71" height="71" />
    <icon src="res/Windows/Square71x71Logo.scale-200.png" width="142" height="142" />
    <icon src="res/Windows/Square71x71Logo.scale-240.png" width="170" height="170" />
```

When `target` attribute is specified every image that matches regexp `/Square71x71Logo(\.scale\-\d+)?\.png/` will be copied to application's `images` directory.

**Comment by vladimir-kotikov** [comment]
This is not yet documented, but we're in process of adding docs and examples for `target` attribute

**Comment by SunboX** [comment]
Oh, thanks for the hint! This is great! :smile:

**Comment by vladimir-kotikov** [comment]
The PR with documentation: https://github.com/apache/cordova-docs/pull/558

**Comment by limebreaker** [comment]
Hello, could it be that the target attr. in:
<icon src="res/windows/storelogo.png" target="StoreLogo" />
 is actually completely ignored as  I always get no img.target in line 360:
 var images = config.getIcons('windows').concat(config.getSplashScreens('windows')); and therefor always "The following image is skipped due to unsupported size".

It seems that the config.getIcons never parses and adds the target attribute. The only way to get it work for me is using  width & height attribute.  Running win 8.1 cordova 6.0.0 , windows 4.3.1

**Comment by vladimir-kotikov** [comment]
@limebreaker, this problem has been fixed in https://github.com/apache/cordova-lib/pull/392

**Pull request closed without merging**
