### PR TITLE
CB-11968: Add support for config-file in config.xml

### PR DESCRIPTION
**Pull request by matrosov-nikita**
### What does this PR do?
Cordova-common changes: https://github.com/apache/cordova-common/pull/2 (should be merged before)
This PR is needed to apply changes using  'device-target' and 'versions' attributes to manifests.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by filmaj** [comment]
I'm not familiar with this changeset enough, but I think this probably needs unit tests :)

Once more, ping @stevengill.

**Comment by matrosov-nikita** [comment]
First we should merge [cordova-common's PR](https://github.com/apache/cordova-common/pull/2) and update cordova-common in node_modules, because this PR uses [a new logic](https://github.com/matrosov-nikita/cordova-windows/blob/a67b25927ad394932a72ebe65b649c0940235ea7/template/cordova/lib/ConfigParser.js#L57) from cordova-common and just processes result specifically for windows platform.

**Comment by stevengill** [comment]
It has been merged. Will try to get a release out this week

**Comment by janpio** [comment]
What is the state of this PR now? All requirements merged?

**Comment by brodybits** [comment]
Should this be included in the next cordova-windows release?

Links:
- <https://issues.apache.org/jira/browse/CB-11968> - original report
- <https://github.com/apache/cordova-common/pull/2> - fix for CB-11968 in cordova-common ALREADY MERGED

**Comment by matrosov-nikita** [comment]
Hi guys, sorry for delay,
`cordova-common` has been updated, so that PR is ready to merge, but since it's pretty old, we should make sure that's still working as expected after rebase.
I'll try to double-check this feature today.

**Comment by matrosov-nikita** [comment]
@janpio Still works as expected, rebased.

**Comment by janpio** [comment]
Can you talk us through the changes (most of them just seems to be moving code around?) and how to use this please?

**Comment by shazron** [comment]
Thanks @matrosov-nikita - @janpio  how to use should be evident, check the <config-file> docs, unless I'm not understanding something.

**Comment by matrosov-nikita** [comment]
As @brodybits mentioned, there is a new logic (apache/cordova-common#2) in `cordova-common` that allows us to use `<config-file>` in config.xml (previously we can only use `<config-file>` in the  plugin.xml). And it works fine for android and ios now. But windows platform requires  some additional changes because we need to distribute the changes in manifests according to `device-target` and `versions` attributes.

So, this PR includes two changes:
1) Moves logic for demuxing changes in manifests from `PluginInfo.js` because it's not only for plugin.xml now.
2) Use windows config parser for prepare, it's decorator for `cordova-common` parser (see `getConfigFiles` method). We just get changes from `cordova-common` 
and process them specifically for windows platform.

How to use it:

Just add the following code to config.xml and call `cordova prepare windows`

```
<platform name="windows">
    <config-file parent="/Package/Capabilities" target="package.appxmanifest">
        <Capability Name="should-exist-for-all-appxmanifest-target-files" />
    </config-file>
    <config-file device-target="windows" parent="/Package/Capabilities" target="package.appxmanifest" versions="=8.1.0">
        <Capability Name="should-exist-for-win81-win-only" />
    </config-file>
    <config-file device-target="phone" parent="/Package/Capabilities" target="package.appxmanifest" versions="=8.1.0">
        <Capability Name="should-exist-for-win81-phone-only" />
    </config-file>
    <config-file parent="/Package/Capabilities" target="package.appxmanifest" versions="&gt;=10.0.0">
        <Capability Name="should-exist-in-win10-only" />
    </config-file>
</platform>
```

Result:

packages.phone.appxmanifest:

```
<Capabilities>
    <Capability Name="internetClientServer" />
    <Capability Name="should-exist-for-all-appxmanifest-target-files" />
    <Capability Name="should-exist-for-win81-phone-only" />
</Capabilities>
```

package.windows.appxmanifest:

```
<Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="should-exist-for-all-appxmanifest-target-files" />
    <Capability Name="should-exist-for-win81-win-only" />
</Capabilities>
```

package.windows10.appxmanifest:

```
<Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="should-exist-for-all-appxmanifest-target-files" />
    <Capability Name="should-exist-in-win10-only" />
</Capabilities>
```

Docs for using `config-file` in plugin.xml - https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#config-file

@janpio Let me know if you have any questions.

**Comment by matrosov-nikita** [comment]
Yeah, this feature isn't documented yet. But I guess it works in a similar way with `<config-file>` from plugin.xml. So, we should probably share or duplicate that for config file.

As for unit tests, that's good point, I think that we need the test which verifies that `WindowsConfigParser` is used for `prepare` (not cordova-common parser). I'll try to add it tomorrow.

**Comment by shazron** [comment]
We could just put the section and point it to the plugin.xml docs if its the same. See edit-config in config.xml:
screen shot 2018-01-24 at 7 03 54 am

**Comment by matrosov-nikita** [comment]
@janpio @shazron 
I've made [PR](https://github.com/apache/cordova-docs/pull/783)  to `cordova-docs`  and added test, but it's failed since we [reverted updating of node_modules](https://github.com/apache/cordova-windows/commit/18eb64389700667608c0186da1e5112afc67e23e).

This PR requires `cordova-common@2.1.0`

**Comment by janpio** [comment]
I revertet that commit because it was part of the release process of 5.1.0 which I canceled. Would the correct way to "fix" this be to actually update `node_modules` in this PR?

**Comment by janpio** [comment]
The failures you are seeing now are expected as `master` wasn't being tested for the last few months after a breaking change was introduced (and nobody bothered to check what CI actually did). I am working on fixing these tests in `master` right now.

**Comment by matrosov-nikita** [comment]
Well, thanks for the heads-up, @janpio

**Comment by brodybits** [comment]
> The failures you are seeing now are expected as master wasn't being tested for the last few months after a breaking change was introduced

@janpio can you give us an explanation of what the breaking change was and if it affected any releases already published?

I was expecting and hoping to see the new cordova-windows release 1-2 weeks ago, with the fix for startup crash on Windows 8.1 (<https://issues.apache.org/jira/browse/CB-13175> / PR #239). This is major for me since I still have to test a special Cordova sqlite plugin version on Windows 8.1 build. Any idea when we can see this release?

+1 for fixing CI tests, though I would give higher priority to releasing a fix for the startup crash issue.

**Comment by janpio** [comment]
@brodybits see #246 for the PR fixing this (problem only got introduced after last release, so no effect on released and published versions).

Without passing tests I can't do a release, which is why this is all taking much longer than hoped (and expected). But noone noticed the broken tests before, so nothing I can do about that now (but fixing it myself).

(Problem with https://issues.apache.org/jira/browse/CB-13834 by the way is that I can not reproduce it locally - so help very much welcome in doing so.)

**Comment by janpio** [comment]
Oh yes, and I could use a review on https://github.com/apache/cordova-windows/pull/246 of course @brodybits so I don't just have to merge my own code changes without anyone approving it. Please have a look, without that we can't progress at all.

**Comment by brodybits** [comment]
Thanks @janpio for the detailed response and thanks for merging this one. I will take a look at #246 and continue the discussion there.

**Comment by DennisSmolek** [comment]
Is this functionality live? I haven't seen any documentation on how to add to the config besides plugins...

**Comment by janpio** [comment]
I don't think the documentation was updated, only the actual code. (PRs to the docs are highly appreciated of course!)

**Pull request merged**
