### PR TITLE
CB-10480 Remove Windows 8 template from cordova-windows

### PR DESCRIPTION
**Pull request by daserge**
[Jira issue](https://issues.apache.org/jira/browse/CB-10480)

### CODE REVIEW

**Comment by csantanapr** [comment]
For what version is this for? cordova-windows@5.0.0 ?

**Comment by daserge** [comment]
This will be a breaking change, so yes, probably for cordova-windows@5.

**Comment by purplecabbage** [comment]
+1
Windows 8.0 has been deprecated since Apr 13, 2015, let's cleanup so we can provide better focus.

**Comment by sgrebnov** [comment]
Reviewed changes, :+1:

**Pull request merged**
