### PR TITLE
CB-9335: Windows quality-of-life improvements.

### PR DESCRIPTION
**Pull request by robpaveza**
This change documents the separator between and how to specify multiple architectures using the
--archs argument to build and run.

Removed the Windows 8 project from the Visual Studio 2013 solution.  It is still possible to use Visual Studio 2013 to work on the Windows 8 project; to do so, load the CordovaApp.vs2012.sln into Visual Studio 2013.

### CODE REVIEW

**Comment by purplecabbage** [comment]
Looks great!

**Comment by TimBarham** [comment]
Looks good to me.

Have you verified no changes need to be made to `cordova-lib/src/util/windows/jsprojManager.js` (adding/removing plugins that use `<lib-file>` or `<framework>` elements for the windows platform)? Also, you might want to update `cordova-lib/spec-plugman/projects/windows/CordovaApp.sln` to reflect this change.

Assuming that's all good, is this ready to be merged?

**Comment by robpaveza** [comment]
@TimBarham We don't require any changes to jsprojManager because this change didn't change any .jsprojes, only .slns.  

I'll go ahead and make the corresponding change to cordova-lib, but yes, this should be ready to merge then.

**Comment by TimBarham** [comment]
Note that `jsprojManager` does manipulate the sln files (see `addProjectReference()` and `removeProjectReference()`, which correspond to a `framework` element with `type="projectReference"`).

**Pull request closed without merging**
