### PR TITLE
[CB-13861] Update TargetPlatformVersion

### PR DESCRIPTION
**Pull request by purplecabbage**
Update TargetPlatformVersion to 10.0.10586.0

### Platforms affected
cordova-windows (windows 10 projects)

### What does this PR do?
Updates TargetPlatformVersion to 10.0.10586.0

### What testing has been done on this change?
works for me!

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by brodybits** [comment]
Works for me on both Visual Studio 2015 and Visual Studio 2017. Ship it!

**Comment by janpio** [comment]
What does `cordova requirements windows` return for you?

**Comment by brodybits** [comment]
If I would do `cordova platform add https://github.com/apache/cordova-windows` in a new project then do `cordova requirements windows` I get the following output:

```sh
Requirements check results for windows:
Windows OS: not installed
Error: Cannot read property 'os' of undefined
(node:5776) UnhandledPromiseRejectionWarning: CordovaError: Some of requirements check failed
    at C:\Users\brodybits\AppData\Local\nvs\node\9.5.0\x64\node_modules\cordova\src\cli.js:414:27
    at _fulfilled (C:\Users\brodybits\AppData\Local\nvs\node\9.5.0\x64\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\brodybits\AppData\Local\nvs\node\9.5.0\x64\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\brodybits\AppData\Local\nvs\node\9.5.0\x64\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\Users\brodybits\AppData\Local\nvs\node\9.5.0\x64\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
    at flush (C:\Users\brodybits\AppData\Local\nvs\node\9.5.0\x64\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:5776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Same result if I would do `cordova platform add https://github.com/apache/cordova-windows#CB-13861` then `cordova requirements windows`.

**Comment by janpio** [comment]
Ouch. We might want to look into that later ;)

**Comment by brodybits** [comment]
> Ouch. We might want to look into that later ;)

@janpio what are your results? Any different?

**Comment by janpio** [comment]
None right now, just setting up to test/release tomorrow and wanted to make sure I know which combination is known good ;)

**Comment by janpio** [comment]
This turned out to be a bigger problem than expected. It is not a blocking issue at https://issues.apache.org/jira/browse/CB-13870

What errors were you trying to solve by changing `TargetPlatformVersion` @purplecabbage and @brodybits? What should I look for the "before" state?

**Comment by brodybits** [comment]
> What should I look for the "before" state?

Without the proposed change I get the following output if I do `npm run test-e2e` in my workarea:

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\JavaScript\Microsoft.VisualStudio.JavaScript.UAP.targets(82,3): error : "10.0.10240.0" is not a supported value for TargetPlatformVersion. Please change it on the Project Property page. [C:\Users\brodybits\Documents\cbwork\cordova-windows\testcreate ??
```

**Comment by janpio** [comment]
The error message you posted contains `VisualStudio\v14.0` which is Visual Studio 2015. https://issues.apache.org/jira/browse/CB-13861 specifically mentions Visual Studio 2017. What is the connection here?

**Comment by janpio** [comment]
I can now confirm this error message with (only) Visual Studio 2017 installed:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\JavaScript\Microsoft.VisualStudio.JavaScript.UAP.targets(84,3): error : "10.0.10240.0" is not a supported value for TargetPlatformVersion. Please change it on the Project Property page. [C:\Projects\Cordova\cordova-windows\testcreate ??\CordovaApp.Windows10.jsproj]
```

**Comment by janpio** [comment]
Unfortunately I can not confirm that changing the value to `...10586...` fixes the issue:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\JavaScript\Microsoft.VisualStudio.JavaScript.UAP.targets(84,3): error : "10.0.10586.0" is not a supported value for TargetPlatformVersion. Please change it on the Project Property page. [C:\Projects\Cordova\cordova-windows\testcreate ??\CordovaApp.Windows10.jsproj]
```

Is this maybe related to the actually installed local versions of Windows SDK?
Could you both please check which ones you have installed?

(When creating an actual project, this value is replaced by the highest available I think, so this might really only be an issue with `npm test`/`npm run test-e2e` but not in actual usage.)

**Comment by brodybits** [comment]
> Is this maybe related to the actually installed local versions of Windows SDK?

I would think so

> Could you both please check which ones you have installed?

I will check sometime later

**Comment by janpio** [comment]
Can confirm, I currently only have `10.0.16299.0` (newest) installed. These tests only succeed if I change it to that version.

Let me confirm that I can actually build an app without updating this value when I install the branch I am currently working on.

**Comment by janpio** [comment]
So I installed my branch which is giving me errors on running the test. 

On `cordova platform add ...` it creates a `CordovaApp.Windows10.jsproj` file with:
```
    <PropertyGroup>
        <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
        <TargetPlatformVersion>10.0.16299.0</TargetPlatformVersion>
        <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
        <MinimumVisualStudioVersion>14.0</MinimumVisualStudioVersion>
        <UapDefaultAssetScale>100</UapDefaultAssetScale>
    </PropertyGroup>
```

So it updates the `TargetPlatformVersion` to the current version somewhere.

Yes, there is some code for that in `prepare.js` and this is actually executed during `cordova platform add ...`.

Which means that the tests should probably/maybe do something similar instead of this PR here, right? This PR is only making it possible to run the tests with a very specific setup.

**Comment by janpio** [comment]
Problem is that `prepare` is not available on the command line... so I had to implement that. 
Will open an issue and PR later.

**Comment by janpio** [comment]
See https://github.com/apache/cordova-windows/pull/254 as a replacement. Would be nice if you could check that out and run it locally to see if the tests succeed.

**Comment by janpio** [comment]
#254 is now in a state to be tested and reviewed.

**Pull request closed without merging**
