### PR TITLE
CB-9057: Replaced the Windows 10 Preview version of WinJS with the latest base.js

### PR DESCRIPTION
**Pull request by robpaveza**
Pulled the WinJS branch from github and built it then migrated to only base.js.  This removes the WinJS UI dependency and reduces build overhead.

### CODE REVIEW

**Comment by purplecabbage** [comment]
Will this create a conflict if someone wants to use WinJS UI ?

**Comment by robpaveza** [comment]
Sorry I commented on the Jira, not the PR:

No. Someone just drops the UI components (css/ui-light or dark, fonts/symbols.ttf, and ui.js) into the project.

You can get those components presently from git-cloning winjs from GitHub, and then doing a grunt build on the cloned repo.

**Comment by nikhilkh** [comment]
I think the reference here: https://github.com/apache/cordova-windows/blob/master/cordova-js-src/platform.js needs to be updated to point to base.js

**Comment by robpaveza** [comment]
Right you are.  I've rebased and updated the PR.

**Comment by robpaveza** [comment]
Also I made a corresponding PR for Cordova.js.

https://github.com/apache/cordova-js/pull/113

**Comment by peterjuras** [comment]
What is the recommended way to integrate ui.js now into a cordova app?

I don't want to include ui.js into every app version (iOS, Android & UWP) but just into UWP. Before this change cordova took care of that.

**Comment by purplecabbage** [comment]
Sorry Peter, 
You are about 2 years too late. What is the goal you are trying to achieve?  
It is difficult to use different UI frameworks for different platforms ... although it IS possible through plugins.

**Comment by peterjuras** [comment]
I'm trying to include ui.js only in the Windows build of our app. Do you know a plugin which could achieve this?

**Comment by purplecabbage** [comment]
http://cordova.apache.org/docs/en/6.x/guide/cli/index.html#using-merges-to-customize-each-platform

**Pull request closed without merging**
