### PR TITLE
CB-10446 Windows 10 Cordova Application restart instead of resume

### PR DESCRIPTION
**Pull request by daserge**
[Jira issue](https://issues.apache.org/jira/browse/CB-10446)

### CODE REVIEW

**Comment by nikhilkh** [comment]
@rakatyal to review.

**Comment by nikhilkh** [comment]
LGTM

**Comment by rakatyal** [comment]
Looks good. Just a question, do we intend to revert this once the windows team fix it on their side? Is there any harm in including the package name in the URIPrefix for other win platforms as well?

**Comment by nikhilkh** [comment]
I don't see much downside in keeping this always.

**Comment by daserge** [comment]
@nikhilkh, @rakatyal, thank you for the review.
Updated to use `Identity.Name` for 8.1 as well for consistency.

**Comment by rakatyal** [comment]
Thanks @daserge. LGTM.

**Comment by gasby82** [comment]
Hi,
I have the same problem with windows 8.1. My environment is cordova version 6.2.0 and windows platform version 4.3.2. How can i fix it? Any workaround?
Thanks

**Comment by daserge** [comment]
Hi @gasby82, 
It might be caused by this bug: https://issues.apache.org/jira/browse/CB-11443
Try using the master version of the platform as it has been fixed but is not yet released:
`cordova platform rm windows && cordova platform add https://github.com/apache/cordova-windows`

**Comment by gasby82** [comment]
Hi @daserge,
thanks for the reply but with platform version 4.5.0-dev it doesn't work. When I resume my app, it restarts. In Windows 10 it works. Do you know any workaround?

**Comment by gasby82** [comment]
Hi @daserge,
Now it works. Thanks for the support. The problem was due to an incompatibility in the javascript framework. It does not depend on cordova.

**Comment by daserge** [comment]
@gasby82, thanks for the info.
Do you mean `WinJS` by `javascript framework`?

**Comment by mdudek** [comment]
Hi @gasby82, what was the problem with 'javascript framework'?

**Pull request merged**
