### PR TITLE
CB-9456 Fixed windows app crash on startup

### PR DESCRIPTION
**Pull request by alsorokin**
https://issues.apache.org/jira/browse/CB-9456

### CODE REVIEW

**Comment by sgrebnov** [comment]
:+1:

**Comment by robpaveza** [comment]
LGTM

**Comment by purplecabbage** [comment]
Seems to be some redundancy between this and 563a3f3decd267554f25e66ba131779de66089d0
Anyways, it is working, so I will merge.

**Comment by purplecabbage** [comment]
My attempts to keep git-logs clean mean this did not auto-close ... ugh
It has been merged, please close this pr.

**Pull request closed without merging**
